package mcpclient

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/tmc/langchaingo/tools"
)

// MCPBridgeTool implements the langchaingo/tools.Tool interface
// and proxies requests dynamically to the stateless MCP Server.
type MCPBridgeTool struct {
	session *mcp.ClientSession
	name    string
	desc    string
	schema  interface{}
}

// Name returns the name of the tool as defined by the MCP server.
func (t *MCPBridgeTool) Name() string { return t.name }

// Description returns the description of the tool as defined by the MCP server.
func (t *MCPBridgeTool) Description() string { return t.desc }

// Schema returns the JSON schema of the tool as defined by the MCP server.
func (t *MCPBridgeTool) Schema() interface{} { return t.schema }

// Call executes the tool via the stateless MCP StreamableHTTP transport.
func (t *MCPBridgeTool) Call(ctx context.Context, input string) (string, error) {
	var args any
	input = strings.TrimSpace(input)

	// Since we are using structured schemas, input is usually a raw JSON string generated by the LLM
	if strings.HasPrefix(input, "{") && strings.HasSuffix(input, "}") {
		var m map[string]any
		if err := json.Unmarshal([]byte(input), &m); err == nil {
			args = m
		} else {
			args = input
		}
	} else {
		args = input
	}

	params := &mcp.CallToolParams{
		Name:      t.name,
		Arguments: args,
	}

	// Because the connection is stateless, _meta capabilities and versioning 
	// are automatically injected by the Go SDK during this call.
	res, err := t.session.CallTool(ctx, params)
	if err != nil {
		return "", fmt.Errorf("mcp tool call failed: %w", err)
	}

	if res.IsError {
		var sb strings.Builder
		for _, c := range res.Content {
			if tc, ok := c.(*mcp.TextContent); ok {
				sb.WriteString(tc.Text)
			}
		}
		return fmt.Sprintf("Error from tool: %s", sb.String()), nil
	}

	// Concatenate result text
	var sb strings.Builder
	for _, c := range res.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			sb.WriteString(tc.Text)
		}
	}
	return sb.String(), nil
}

// GenerateLangChainTools takes discovered MCP tools and wraps them as LangChain tools.
func GenerateLangChainTools(session *mcp.ClientSession, mcpTools []*mcp.Tool) []tools.Tool {
	var lcTools []tools.Tool
	for _, mt := range mcpTools {
		b, _ := json.Marshal(mt)
		var m map[string]interface{}
		json.Unmarshal(b, &m)
		
		schema := m["inputSchema"]
		if schema == nil {
			schema = m["InputSchema"]
		}

		lcTools = append(lcTools, &MCPBridgeTool{
			session: session,
			name:    mt.Name,
			desc:    mt.Description,
			schema:  schema,
		})
	}
	return lcTools
}
