package main

import (
	"bufio"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/tmc/langchaingo/agents"
	"github.com/tmc/langchaingo/callbacks"
	"github.com/tmc/langchaingo/chains"
	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/llms/openai"
	"github.com/tmc/langchaingo/schema"
	"github.com/tmc/langchaingo/tools"
)

// ============================================================================
// Config & Env Helpers
// ============================================================================

func loadEnv() {
	file, err := os.Open(".env")
	if err != nil {
		log.Println("Note: .env file not found, using system environment variables.")
		return
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			if (strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"")) ||
				(strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'")) {
				value = value[1 : len(value)-1]
			}
			os.Setenv(key, value)
		}
	}
}

func getEnv(key, defaultVal string) string {
	if val := os.Getenv(key); val != "" {
		return val
	}
	return defaultVal
}

// ============================================================================
// MCP Tool Adapter (Structured arguments)
// ============================================================================

type MCPToolWrapper struct {
	session *mcp.ClientSession
	name    string
	desc    string
	schema  map[string]any
}

func (w *MCPToolWrapper) ParameterSchema() map[string]any {
	return w.schema
}

func (w *MCPToolWrapper) Name() string        { return w.name }
func (w *MCPToolWrapper) Description() string { return w.desc }

func (w *MCPToolWrapper) Call(ctx context.Context, input string) (string, error) {
	var args any
	input = strings.TrimSpace(input)

	// Since we are using structured schemas, input is the raw JSON string generated by the LLM
	if strings.HasPrefix(input, "{") && strings.HasSuffix(input, "}") {
		var m map[string]any
		if err := json.Unmarshal([]byte(input), &m); err == nil {
			args = m
		} else {
			args = input
		}
	} else {
		// Fallback for simple raw string formats
		if w.name == "query_postgres" {
			args = map[string]any{
				"sql_query": input,
				"question":  "Executed via Go client agent",
			}
		} else {
			args = input
		}
	}

	params := &mcp.CallToolParams{
		Name:      w.name,
		Arguments: args,
	}

	res, err := w.session.CallTool(ctx, params)
	if err != nil {
		return "", err
	}

	if res.IsError {
		var sb strings.Builder
		for _, c := range res.Content {
			if tc, ok := c.(*mcp.TextContent); ok {
				sb.WriteString(tc.Text)
			}
		}
		return fmt.Sprintf("Error: %s", sb.String()), nil
	}

	var sb strings.Builder
	for _, c := range res.Content {
		if tc, ok := c.(*mcp.TextContent); ok {
			sb.WriteString(tc.Text)
		}
	}
	return sb.String(), nil
}

// ============================================================================
// Custom Structured Report Exporter Tool
// ============================================================================

type ExcelExportTool struct{}

func (e ExcelExportTool) Name() string { return "export_excel" }
func (e ExcelExportTool) Description() string {
	return "Generates a beautifully styled multi-sheet BCG Excel report. Input must specify 'records' array of objects, 'question', and 'sql_query'."
}

func (e ExcelExportTool) ParameterSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"records": map[string]any{
				"type": "array",
				"items": map[string]any{
					"type": "object",
				},
				"description": "The array of output rows/records to export.",
			},
			"question": map[string]any{
				"type":        "string",
				"description": "The user's natural language query.",
			},
			"sql_query": map[string]any{
				"type":        "string",
				"description": "The raw SQL query that produced the records.",
			},
		},
		"required": []string{"records", "question", "sql_query"},
	}
}

func (e ExcelExportTool) Call(ctx context.Context, input string) (string, error) {
	var payload struct {
		Records  []map[string]any `json:"records"`
		Question string           `json:"question"`
		SQL      string           `json:"sql_query"`
	}

	if err := json.Unmarshal([]byte(input), &payload); err != nil {
		return "", fmt.Errorf("failed to parse structured input JSON: %v. Raw input: %s", err, input)
	}

	// Handle empty records gracefully
	if len(payload.Records) == 0 {
		return "No records found to export to Excel.", nil
	}

	// Create a temp file to pass payload to python excel_generator.py
	tempFile, err := os.CreateTemp("", "ul_excel_payload_*.json")
	if err != nil {
		return "", fmt.Errorf("failed to create temp file: %v", err)
	}
	defer os.Remove(tempFile.Name())
	defer tempFile.Close()

	type pythonPayload struct {
		Records   []map[string]any `json:"records"`
		Question  string           `json:"question"`
		SQL       string           `json:"sql"`
		ExportDir string           `json:"export_dir"`
	}
	pData := pythonPayload{
		Records:   payload.Records,
		Question:  payload.Question,
		SQL:       payload.SQL,
		ExportDir: "./data/excel_exports",
	}

	enc := json.NewEncoder(tempFile)
	if err := enc.Encode(pData); err != nil {
		return "", fmt.Errorf("failed to encode payload: %v", err)
	}

	// Run Python Excel script
	cmd := exec.CommandContext(ctx, "python", "excel_generator.py", tempFile.Name())
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("python script execution failed: %v. Output: %s", err, string(out))
	}

	filename := strings.TrimSpace(string(out))
	lines := strings.Split(filename, "\n")
	filename = strings.TrimSpace(lines[len(lines)-1])

	downloadURL := fmt.Sprintf("http://localhost:%s/download/%s", getEnv("MCP_SERVER_PORT", "10015"), filename)
	return fmt.Sprintf("Excel report generated successfully!\nFilename: %s\nDownload Link: %s", filename, downloadURL), nil
}

// ============================================================================
// Streaming Callbacks Handler
// ============================================================================

type StreamCallback struct {
	callbacks.SimpleHandler
	OnLLMToken  func(token string)
	OnLLMEnd    func(res *llms.ContentResponse)
	OnToolStart func(input string)
	OnToolEnd   func(output string)
}

func (s *StreamCallback) HandleStreamingFunc(ctx context.Context, chunk []byte) {
	if s.OnLLMToken != nil {
		s.OnLLMToken(string(chunk))
	}
}

func (s *StreamCallback) HandleLLMGenerateContentEnd(ctx context.Context, res *llms.ContentResponse) {
	if s.OnLLMEnd != nil {
		s.OnLLMEnd(res)
	}
}

func (s *StreamCallback) HandleToolStart(ctx context.Context, input string) {
	if s.OnToolStart != nil {
		s.OnToolStart(input)
	}
}

func (s *StreamCallback) HandleToolEnd(ctx context.Context, output string) {
	if s.OnToolEnd != nil {
		s.OnToolEnd(output)
	}
}

// ============================================================================
// Custom OpenAIFunctionsAgent Implementation (Structured Tool Calling)
// ============================================================================

type CustomOpenAIAgent struct {
	LLM              llms.Model
	Tools            []tools.Tool
	OutputKey        string
	CallbacksHandler callbacks.Handler
	SystemPrompt     string
	History          []llms.ChatMessage
}

var _ agents.Agent = (*CustomOpenAIAgent)(nil)

func (a *CustomOpenAIAgent) GetInputKeys() []string  { return []string{"input"} }
func (a *CustomOpenAIAgent) GetOutputKeys() []string { return []string{a.OutputKey} }
func (a *CustomOpenAIAgent) GetTools() []tools.Tool  { return a.Tools }

func (a *CustomOpenAIAgent) Plan(
	ctx context.Context,
	intermediateSteps []schema.AgentStep,
	inputs map[string]string,
	options ...chains.ChainCallOption,
) ([]schema.AgentAction, *schema.AgentFinish, error) {
	var messages []llms.ChatMessage

	// 1. System Prompt
	messages = append(messages, llms.SystemChatMessage{Content: a.SystemPrompt})

	// 2. Conversation History
	messages = append(messages, a.History...)

	// 3. Human Message
	messages = append(messages, llms.HumanChatMessage{Content: inputs["input"]})

	// 4. Scratchpad (Intermediate steps)
	scratchPad := a.constructScratchPad(intermediateSteps)
	messages = append(messages, scratchPad...)

	// Convert chat messages to ContentPart slice
	mcList := make([]llms.MessageContent, len(messages))
	for i, msg := range messages {
		role := msg.GetType()
		text := msg.GetContent()

		var mc llms.MessageContent
		switch p := msg.(type) {
		case llms.ToolChatMessage:
			mc = llms.MessageContent{
				Role: role,
				Parts: []llms.ContentPart{llms.ToolCallResponse{
					ToolCallID: p.ID,
					Content:    p.Content,
				}},
			}
		case llms.AIChatMessage:
			if len(p.ToolCalls) > 0 {
				toolCallParts := make([]llms.ContentPart, 0, len(p.ToolCalls))
				for _, tc := range p.ToolCalls {
					toolCallParts = append(toolCallParts, llms.ToolCall{
						ID:           tc.ID,
						Type:         tc.Type,
						FunctionCall: tc.FunctionCall,
					})
				}
				mc = llms.MessageContent{
					Role:  role,
					Parts: toolCallParts,
				}
			} else {
				mc = llms.MessageContent{
					Role:  role,
					Parts: []llms.ContentPart{llms.TextContent{Text: text}},
				}
			}
		default:
			mc = llms.MessageContent{
				Role:  role,
				Parts: []llms.ContentPart{llms.TextContent{Text: text}},
			}
		}
		mcList[i] = mc
	}

	var stream func(ctx context.Context, chunk []byte) error
	if a.CallbacksHandler != nil {
		stream = func(ctx context.Context, chunk []byte) error {
			a.CallbacksHandler.HandleStreamingFunc(ctx, chunk)
			return nil
		}
	}

	callOpts := []llms.CallOption{
		llms.WithStreamingFunc(stream),
	}

	funcs := a.functions()
	callOpts = append(callOpts, llms.WithFunctions(funcs))

	log.Printf("CustomOpenAIAgent.Plan inputs: %+v", inputs)
	log.Printf("CustomOpenAIAgent.Plan sending %d messages:", len(mcList))
	for idx, mc := range mcList {
		log.Printf("  Message [%d] Role: %q", idx, mc.Role)
		for pIdx, part := range mc.Parts {
			switch p := part.(type) {
			case llms.TextContent:
				preview := p.Text
				if len(preview) > 200 {
					preview = preview[:200] + "..."
				}
				log.Printf("    Part [%d] TextContent: %s", pIdx, preview)
			case llms.ToolCall:
				log.Printf("    Part [%d] ToolCall: ID=%s, Name=%s, Args=%s", pIdx, p.ID, p.FunctionCall.Name, p.FunctionCall.Arguments)
			case llms.ToolCallResponse:
				preview := p.Content
				if len(preview) > 200 {
					preview = preview[:200] + "..."
				}
				log.Printf("    Part [%d] ToolCallResponse: ID=%s, Content=%s", pIdx, p.ToolCallID, preview)
			default:
				log.Printf("    Part [%d] Unknown Part: %T", pIdx, part)
			}
		}
	}

	res, err := a.LLM.GenerateContent(ctx, mcList, callOpts...)
	if err != nil {
		return nil, nil, err
	}

	return a.parseOutput(res)
}

func (a *CustomOpenAIAgent) functions() []llms.FunctionDefinition {
	res := make([]llms.FunctionDefinition, 0)
	for _, tool := range a.Tools {
		var params map[string]any
		if schematized, ok := tool.(interface{ ParameterSchema() map[string]any }); ok {
			params = schematized.ParameterSchema()
		} else {
			// Fallback schema for simple string tools
			params = map[string]any{
				"type": "object",
				"properties": map[string]any{
					"__arg1": map[string]any{"type": "string"},
				},
				"required": []string{"__arg1"},
			}
		}
		res = append(res, llms.FunctionDefinition{
			Name:        tool.Name(),
			Description: tool.Description(),
			Parameters:  params,
		})
	}
	return res
}

func (a *CustomOpenAIAgent) constructScratchPad(steps []schema.AgentStep) []llms.ChatMessage {
	if len(steps) == 0 {
		return nil
	}

	messages := make([]llms.ChatMessage, 0)
	var currentToolCalls []llms.ToolCall
	var currentLog string

	for i, step := range steps {
		if i == 0 || step.Action.Log != steps[i-1].Action.Log {
			if len(currentToolCalls) > 0 {
				messages = append(messages, llms.AIChatMessage{
					Content:   currentLog,
					ToolCalls: currentToolCalls,
				})
				for j := i - len(currentToolCalls); j < i; j++ {
					messages = append(messages, llms.ToolChatMessage{
						ID:      steps[j].Action.ToolID,
						Content: steps[j].Observation,
					})
				}
				currentToolCalls = nil
			}
			currentLog = step.Action.Log
		}

		currentToolCalls = append(currentToolCalls, llms.ToolCall{
			ID:   step.Action.ToolID,
			Type: "function",
			FunctionCall: &llms.FunctionCall{
				Name:      step.Action.Tool,
				Arguments: step.Action.ToolInput, // ToolInput is already the raw JSON string
			},
		})
	}

	if len(currentToolCalls) > 0 {
		messages = append(messages, llms.AIChatMessage{
			Content:   currentLog,
			ToolCalls: currentToolCalls,
		})
		for j := len(steps) - len(currentToolCalls); j < len(steps); j++ {
			messages = append(messages, llms.ToolChatMessage{
				ID:      steps[j].Action.ToolID,
				Content: steps[j].Observation,
			})
		}
	}

	return messages
}

func (a *CustomOpenAIAgent) parseOutput(contentResp *llms.ContentResponse) ([]schema.AgentAction, *schema.AgentFinish, error) {
	if contentResp == nil || len(contentResp.Choices) == 0 {
		return nil, nil, fmt.Errorf("no choices in response")
	}
	choice := contentResp.Choices[0]

	if len(choice.ToolCalls) > 0 {
		actions := make([]schema.AgentAction, 0, len(choice.ToolCalls))
		for _, toolCall := range choice.ToolCalls {
			functionName := toolCall.FunctionCall.Name
			toolInputStr := toolCall.FunctionCall.Arguments // Keep the raw arguments JSON string

			contentMsg := "\n"
			if choice.Content != "" {
				contentMsg = fmt.Sprintf("responded: %s\n", choice.Content)
			}

			actions = append(actions, schema.AgentAction{
				Tool:      functionName,
				ToolInput: toolInputStr,
				Log:       fmt.Sprintf("Invoking: %s with %s %s", functionName, toolInputStr, contentMsg),
				ToolID:    toolCall.ID,
			})
		}
		return actions, nil, nil
	}

	return nil, &schema.AgentFinish{
		ReturnValues: map[string]any{
			"output": choice.Content,
		},
		Log: choice.Content,
	}, nil
}

// ============================================================================
// Main Execution Entrypoint
// ============================================================================

func main() {
	log.Println("Starting Go Agent Client...")
	loadEnv()

	flag.Parse()
	args := flag.Args()

	// 1. Connect to MCP Server
	mcpPort := getEnv("MCP_SERVER_PORT", "10015")
	mcpURL := fmt.Sprintf("http://localhost:%s/mcp", mcpPort)
	log.Printf("Connecting to Go MCP Server at %s...", mcpURL)

	transport := &mcp.StreamableClientTransport{
		Endpoint:             mcpURL,
		DisableStandaloneSSE: true,
	}
	client := mcp.NewClient(&mcp.Implementation{
		Name:    "Go-Agent-Client",
		Version: "1.0.0",
	}, nil)

	ctx := context.Background()
	session, err := client.Connect(ctx, transport, nil)
	if err != nil {
		log.Fatalf("Failed to connect to MCP Server: %v. Ensure the Go MCP server is running on port %s.", err, mcpPort)
	}
	defer session.Close()

	// 2. Discover MCP tools
	toolsResult, err := session.ListTools(ctx, nil)
	if err != nil {
		log.Fatalf("Failed to fetch tools from server: %v", err)
	}

	var agentTools []tools.Tool
	log.Println("Discovered MCP Server tools:")
	for _, t := range toolsResult.Tools {
		log.Printf("  - %s: %s", t.Name, t.Description)

		var schemaMap map[string]any
		if t.InputSchema != nil {
			if m, ok := t.InputSchema.(map[string]any); ok {
				schemaMap = m
			} else {
				// Serialize/deserialize to get a map[string]any
				if b, err := json.Marshal(t.InputSchema); err == nil {
					json.Unmarshal(b, &schemaMap)
				}
			}
		}

		agentTools = append(agentTools, &MCPToolWrapper{
			session: session,
			name:    t.Name,
			desc:    t.Description,
			schema:  schemaMap,
		})
	}

	// Add our custom report tool
	agentTools = append(agentTools, &ExcelExportTool{})
	log.Printf("  - export_excel (Structured Custom Tool)")

	// 3. Initialize LLM (Azure OpenAI or direct OpenAI)
	var llm llms.Model
	useAzure := strings.ToLower(getEnv("USE_AZURE", "false")) == "true"

	if useAzure {
		log.Println("Initializing Chat Model: Azure OpenAI Integration")
		llm, err = openai.New(
			openai.WithAPIType(openai.APITypeAzure),
			openai.WithBaseURL(getEnv("AZURE_OPENAI_ENDPOINT", "")),
			openai.WithToken(getEnv("AZURE_OPENAI_API_KEY", "")),
			openai.WithAPIVersion(getEnv("AZURE_OPENAI_API_VERSION", "2024-05-01-preview")),
			openai.WithModel(getEnv("AZURE_OPENAI_DEPLOYMENT_NAME", "gpt-4o")),
		)
	} else {
		log.Println("Initializing Chat Model: Native OpenAI Integration")
		llm, err = openai.New(
			openai.WithToken(getEnv("OPENAI_API_KEY", "")),
			openai.WithModel(getEnv("OPENAI_MODEL", "gpt-4o")),
		)
	}
	if err != nil {
		log.Fatalf("Failed to initialize LLM: %v. Check api keys or endpoints configuration.", err)
	}

	// 4. System Prompt
	systemPrompt := `You are an advanced Unilever insights database assistant.
You help users query a PostgreSQL database by generating read-only SQL queries and analyzing table records.
You have access to get_database_schema, query_postgres, and export_excel.

Execution Rules:
1. Always call get_database_schema first to inspect tables and column formats before running a PostgreSQL query.
2. Formulate read-only SQL queries. Do not attempt modifications.
3. Call query_postgres with the constructed SQL query to retrieve records.
4. If the user asks to "export", "download", or "create report/excel" of the results, parse the output records from query_postgres and pass them into the 'export_excel' tool as a valid JSON payload along with the query and context.
5. Provide a friendly natural language response explaining the results clearly. Keep intermediate steps hidden from the final text response.`

	if len(args) > 0 {
		// ====================================================================
		// CLI MODE
		// ====================================================================
		question := strings.Join(args, " ")
		log.Printf("Executing CLI Agent for question: %q", question)

		cb := &StreamCallback{
			OnLLMToken: func(token string) {
				fmt.Print(token)
			},
			OnToolStart: func(input string) {
				fmt.Printf("\n[Tool Call Start] Arguments: %s\n", input)
			},
			OnToolEnd: func(output string) {
				fmt.Printf("\n[Tool Call Result] Length: %d\n", len(output))
			},
			OnLLMEnd: func(res *llms.ContentResponse) {
				if len(res.Choices) > 0 && res.Choices[0].GenerationInfo != nil {
					info := res.Choices[0].GenerationInfo
					fmt.Printf("\n\n[Token Usage] Prompt: %v, Completion: %v, Total: %v\n",
						info["PromptTokens"], info["CompletionTokens"], info["TotalTokens"])
				}
			},
		}

		customAgent := &CustomOpenAIAgent{
			LLM:              llm,
			Tools:            agentTools,
			OutputKey:        "output",
			CallbacksHandler: cb,
			SystemPrompt:     systemPrompt,
		}

		executor := agents.NewExecutor(
			customAgent,
			agents.WithMaxIterations(10),
			agents.WithReturnIntermediateSteps(),
			agents.WithParserErrorHandler(agents.NewParserErrorHandler(func(e string) string {
				return fmt.Sprintf("Parsing error: %s. Formulate function arguments in correct JSON format.", e)
			})),
		)

		res, err := executor.Call(ctx, map[string]any{
			"input": question,
		}, chains.WithCallback(cb))
		if err != nil {
			log.Fatalf("Agent invocation failed: %v", err)
		}

		fmt.Printf("\n\nFinal Agent Answer:\n%s\n", res["output"])

	} else {
		// ====================================================================
		// SERVER/WEB UI MODE
		// ====================================================================
		dashboardPort := getEnv("DASHBOARD_PORT", "10018")
		log.Printf("Starting Web Dashboard on port %s...", dashboardPort)

		http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "text/html")
			w.Write([]byte(HTML_CONTENT))
		})

		http.HandleFunc("/api/schema", func(w http.ResponseWriter, r *http.Request) {
			resp, err := http.Get(fmt.Sprintf("http://localhost:%s/schema", mcpPort))
			if err != nil {
				w.WriteHeader(http.StatusServiceUnavailable)
				json.NewEncoder(w).Encode(map[string]string{"error": "MCP Server offline"})
				return
			}
			defer resp.Body.Close()
			w.Header().Set("Content-Type", "application/json")
			io.Copy(w, resp.Body)
		})

		http.HandleFunc("/download/", func(w http.ResponseWriter, r *http.Request) {
			filename := strings.TrimPrefix(r.URL.Path, "/download/")
			targetURL := fmt.Sprintf("http://localhost:%s/download/%s", mcpPort, filename)
			http.Redirect(w, r, targetURL, http.StatusFound)
		})

		http.HandleFunc("/stream", func(w http.ResponseWriter, r *http.Request) {
			question := r.URL.Query().Get("question")
			if question == "" {
				w.WriteHeader(http.StatusBadRequest)
				w.Write([]byte("Missing question query parameter"))
				return
			}

			w.Header().Set("Content-Type", "text/event-stream")
			w.Header().Set("Cache-Control", "no-cache")
			w.Header().Set("Connection", "keep-alive")
			flusher, ok := w.(http.Flusher)

			writeSSE := func(eventType string, data any) {
				b, _ := json.Marshal(data)
				fmt.Fprintf(w, "event: %s\ndata: %s\n\n", eventType, string(b))
				if ok {
					flusher.Flush()
				}
			}

			writeSSE("info", "Agent workspace initialized.")

			cb := &StreamCallback{
				OnLLMToken: func(token string) {
					writeSSE("token", token)
				},
				OnToolStart: func(input string) {
					writeSSE("tool_start", input)
				},
				OnToolEnd: func(output string) {
					writeSSE("tool_end", output)
				},
				OnLLMEnd: func(res *llms.ContentResponse) {
					var promptTokens, completionTokens, totalTokens int
					if len(res.Choices) > 0 && res.Choices[0].GenerationInfo != nil {
						info := res.Choices[0].GenerationInfo
						if pt, ok := info["PromptTokens"].(int); ok {
							promptTokens = pt
						} else if pt, ok := info["PromptTokens"].(float64); ok {
							promptTokens = int(pt)
						} else if pt, ok := info["prompt_tokens"].(int); ok {
							promptTokens = pt
						}
						if ct, ok := info["CompletionTokens"].(int); ok {
							completionTokens = ct
						} else if ct, ok := info["CompletionTokens"].(float64); ok {
							completionTokens = int(ct)
						} else if ct, ok := info["completion_tokens"].(int); ok {
							completionTokens = ct
						}
						if tt, ok := info["TotalTokens"].(int); ok {
							totalTokens = tt
						} else if tt, ok := info["TotalTokens"].(float64); ok {
							totalTokens = int(tt)
						} else if tt, ok := info["total_tokens"].(int); ok {
							totalTokens = tt
						}
					}
					writeSSE("llm_end", map[string]any{
						"prompt_tokens":     promptTokens,
						"completion_tokens": completionTokens,
						"total_tokens":     totalTokens,
					})
				},
			}

			customAgent := &CustomOpenAIAgent{
				LLM:              llm,
				Tools:            agentTools,
				OutputKey:        "output",
				CallbacksHandler: cb,
				SystemPrompt:     systemPrompt,
			}

			executor := agents.NewExecutor(
				customAgent,
				agents.WithMaxIterations(10),
				agents.WithReturnIntermediateSteps(),
				agents.WithParserErrorHandler(agents.NewParserErrorHandler(func(e string) string {
					return fmt.Sprintf("Parsing error: %s. Formulate function arguments in correct JSON format.", e)
				})),
			)

			log.Printf("Executing stream agent for UI: %q", question)
			res, err := executor.Call(r.Context(), map[string]any{
				"input": question,
			}, chains.WithCallback(cb))

			if err != nil {
				writeSSE("error", fmt.Sprintf("Execution error: %v", err))
			} else {
				writeSSE("final_answer", res["output"])
			}
		})

		serverAddr := ":" + dashboardPort
		log.Printf("Dashboard serving at http://localhost:%s/", dashboardPort)
		if err := http.ListenAndServe(serverAddr, nil); err != nil {
			log.Fatalf("HTTP Dashboard server failed: %v", err)
		}
	}
}

// ============================================================================
// HTML Page Content (Rich Dark Theme with Glassmorphism)
// ============================================================================

const HTML_CONTENT = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UL Insights Agent Dashboard (Go Client)</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-dark: #090d16;
            --bg-card: rgba(20, 30, 48, 0.6);
            --bg-glass: rgba(15, 23, 42, 0.45);
            --border-color: rgba(255, 255, 255, 0.08);
            --border-glow: rgba(0, 166, 81, 0.25);
            --text-primary: #f8fafc;
            --text-secondary: #94a3b8;
            --primary-green: #00a651;
            --primary-green-glow: rgba(0, 166, 81, 0.4);
            --primary-green-dark: #008740;
            --accent-glow: rgba(0, 166, 81, 0.15);
            --danger-red: #ef4444;
            --card-radius: 1.25rem;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Inter', sans-serif;
        }

        body {
            background-color: var(--bg-dark);
            background-image: 
                radial-gradient(at 0% 0%, rgba(0, 166, 81, 0.1) 0px, transparent 50%),
                radial-gradient(at 100% 100%, rgba(20, 30, 48, 0.4) 0px, transparent 50%);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            overflow-x: hidden;
        }

        h1, h2, h3, h4 {
            font-family: 'Outfit', sans-serif;
        }

        header {
            background: rgba(9, 13, 22, 0.85);
            backdrop-filter: blur(12px);
            border-bottom: 1px solid var(--border-color);
            padding: 1.25rem 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: sticky;
            top: 0;
            z-index: 100;
        }

        .logo-section {
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }

        .logo-section h1 {
            font-size: 1.6rem;
            font-weight: 800;
            background: linear-gradient(135deg, #ffffff 40%, var(--primary-green) 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.5px;
        }

        .status-badge {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            background: rgba(0, 166, 81, 0.1);
            border: 1px solid rgba(0, 166, 81, 0.2);
            padding: 0.35rem 0.75rem;
            border-radius: 2rem;
            font-size: 0.8rem;
            font-weight: 500;
            color: var(--primary-green);
        }

        .status-dot {
            width: 8px;
            height: 8px;
            background-color: var(--primary-green);
            border-radius: 50%;
            box-shadow: 0 0 10px var(--primary-green);
            animation: pulse 2s infinite;
        }

        @keyframes pulse {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(0, 166, 81, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(0, 166, 81, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(0, 166, 81, 0); }
        }

        .app-container {
            display: flex;
            flex: 1;
            padding: 2rem;
            gap: 2rem;
            max-width: 1600px;
            margin: 0 auto;
            width: 100%;
        }

        /* Sidebar Schema Explorer */
        .sidebar {
            flex: 0 0 320px;
            background: var(--bg-glass);
            backdrop-filter: blur(16px);
            border: 1px solid var(--border-color);
            border-radius: var(--card-radius);
            padding: 1.5rem;
            display: flex;
            flex-direction: column;
            gap: 1.25rem;
            max-height: calc(100vh - 120px);
            overflow-y: auto;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
        }

        .sidebar-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 0.75rem;
        }

        .sidebar-header h2 {
            font-size: 1.15rem;
            font-weight: 700;
            color: #ffffff;
        }

        .refresh-btn {
            background: transparent;
            border: 1px solid var(--border-color);
            color: var(--text-secondary);
            padding: 0.4rem;
            border-radius: 0.5rem;
            cursor: pointer;
            transition: all 0.2s;
        }

        .refresh-btn:hover {
            color: var(--primary-green);
            border-color: var(--primary-green);
            background: rgba(0, 166, 81, 0.05);
        }

        .schema-list {
            display: flex;
            flex-direction: column;
            gap: 0.75rem;
        }

        .schema-table-item {
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            overflow: hidden;
            background: rgba(255, 255, 255, 0.02);
            transition: all 0.2s;
        }

        .schema-table-item:hover {
            border-color: var(--border-glow);
        }

        .schema-table-header {
            background: rgba(255, 255, 255, 0.04);
            padding: 0.6rem 0.85rem;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            font-weight: 600;
            font-size: 0.9rem;
            color: #f1f5f9;
        }

        .schema-columns {
            padding: 0.6rem 0.85rem;
            background: rgba(0, 0, 0, 0.25);
            display: none;
            flex-direction: column;
            gap: 0.35rem;
            font-size: 0.8rem;
            color: var(--text-secondary);
            border-top: 1px solid var(--border-color);
        }

        .schema-column-detail {
            display: flex;
            justify-content: space-between;
        }

        .schema-column-type {
            color: var(--primary-green);
            font-family: monospace;
        }

        /* Main workbench */
        .workbench {
            flex: 1;
            display: flex;
            flex-direction: column;
            gap: 2rem;
        }

        .glass-card {
            background: var(--bg-glass);
            backdrop-filter: blur(20px);
            border: 1px solid var(--border-color);
            border-radius: var(--card-radius);
            padding: 2rem;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.4);
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
        }

        .input-group {
            display: flex;
            flex-direction: column;
            gap: 0.75rem;
        }

        .input-group label {
            font-size: 0.9rem;
            font-weight: 600;
            color: var(--text-secondary);
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        textarea {
            background-color: rgba(9, 13, 22, 0.65);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            color: var(--text-primary);
            padding: 1rem 1.25rem;
            font-size: 1rem;
            outline: none;
            resize: vertical;
            min-height: 100px;
            transition: all 0.3s;
            box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.4);
        }

        textarea:focus {
            border-color: var(--primary-green);
            box-shadow: 0 0 15px var(--border-glow), inset 0 2px 4px rgba(0, 0, 0, 0.4);
        }

        .action-bar {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .btn {
            background-color: var(--primary-green);
            border: 1px solid var(--primary-green);
            color: #ffffff;
            padding: 0.85rem 1.75rem;
            border-radius: 0.75rem;
            font-weight: 700;
            cursor: pointer;
            transition: all 0.3s;
            display: flex;
            align-items: center;
            gap: 0.6rem;
            font-size: 0.95rem;
            text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
            box-shadow: 0 4px 15px var(--primary-green-glow);
        }

        .btn:hover:not(:disabled) {
            background-color: var(--primary-green-dark);
            border-color: var(--primary-green-dark);
            box-shadow: 0 6px 20px rgba(0, 166, 81, 0.6);
            transform: translateY(-1px);
        }

        .btn:disabled {
            background-color: rgba(255, 255, 255, 0.05);
            border-color: var(--border-color);
            color: var(--text-secondary);
            cursor: not-allowed;
            box-shadow: none;
        }

        /* Real-time Agent Log and Output Display */
        .agent-output-container {
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
            min-height: 250px;
        }

        .output-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 0.75rem;
        }

        .output-header h3 {
            font-size: 1.25rem;
            font-weight: 700;
            color: #ffffff;
        }

        .log-console {
            background-color: rgba(5, 7, 12, 0.85);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            padding: 1.25rem;
            max-height: 400px;
            overflow-y: auto;
            font-family: 'Courier New', Courier, monospace;
            font-size: 0.85rem;
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
            box-shadow: inset 0 2px 8px rgba(0, 0, 0, 0.5);
        }

        .log-line {
            display: flex;
            flex-direction: column;
            gap: 0.25rem;
            border-left: 2px solid var(--border-color);
            padding-left: 0.75rem;
        }

        .log-line.system { border-color: var(--text-secondary); color: var(--text-secondary); }
        .log-line.tool { border-color: var(--primary-green); color: #a7f3d0; }
        .log-line.token { border-color: transparent; padding-left: 0; color: #e2e8f0; font-family: 'Inter', sans-serif; font-size: 0.95rem; white-space: pre-wrap; line-height: 1.6; }

        .log-line.tool-box {
            background-color: rgba(0, 166, 81, 0.05);
            border: 1px solid rgba(0, 166, 81, 0.15);
            border-radius: 0.5rem;
            padding: 0.75rem;
            margin-top: 0.5rem;
        }

        .log-line.tool-box summary {
            cursor: pointer;
            font-weight: 600;
            color: var(--primary-green);
            outline: none;
            font-size: 0.85rem;
        }

        .log-line.tool-box pre {
            margin-top: 0.5rem;
            white-space: pre-wrap;
            font-size: 0.8rem;
            color: #d1d5db;
            max-height: 200px;
            overflow-y: auto;
        }

        /* final answer display */
        .final-answer-box {
            background-color: rgba(255, 255, 255, 0.02);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            padding: 1.5rem;
            line-height: 1.7;
            font-size: 1rem;
            display: none;
            animation: fadeIn 0.4s ease;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .token-usage-bar {
            display: flex;
            gap: 1.5rem;
            font-size: 0.8rem;
            color: var(--text-secondary);
            justify-content: flex-end;
            margin-top: 0.5rem;
        }

        .usage-metric {
            display: flex;
            align-items: center;
            gap: 0.25rem;
        }

        .usage-metric strong {
            color: var(--primary-green);
        }

        .spinner {
            border: 3px solid rgba(255, 255, 255, 0.1);
            border-top: 3px solid var(--primary-green);
            border-radius: 50%;
            width: 24px;
            height: 24px;
            animation: spin 1s linear infinite;
            display: none;
        }

        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    </style>
</head>
<body>

    <header>
        <div class="logo-section">
            <div class="status-badge">
                <div class="status-dot"></div>
                <span>Go Agent Connected</span>
            </div>
            <h1>Unilever Insights Agent</h1>
        </div>
    </header>

    <div class="app-container">
        <!-- Sidebar DB Schema Explorer -->
        <aside class="sidebar">
            <div class="sidebar-header">
                <h2>Database Schema</h2>
                <button class="refresh-btn" id="refreshSchema" title="Refresh schema">
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"/></svg>
                </button>
            </div>
            <div class="schema-list" id="schemaList">
                <div style="text-align: center; color: var(--text-secondary); font-size: 0.85rem; padding: 2rem 0;">
                    Loading database tables...
                </div>
            </div>
        </aside>

        <!-- Main workbench -->
        <main class="workbench">
            <div class="glass-card">
                <div class="input-group">
                    <label for="queryInput">Unilever natural language query</label>
                    <textarea id="queryInput" placeholder="Show me all products with prices higher than 10, and export it as an Excel report..."></textarea>
                </div>
                <div class="action-bar">
                    <div class="spinner" id="spinner"></div>
                    <button class="btn" id="runBtn">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
                        Run Agent
                    </button>
                </div>
            </div>

            <!-- Agent Execution & Streams -->
            <div class="glass-card agent-output-container">
                <div class="output-header">
                    <h3>Agent Workspace console</h3>
                </div>
                
                <div class="log-console" id="logConsole">
                    <div class="log-line system">Ready for questions. Console logs and thinking tokens will stream here...</div>
                </div>

                <div class="final-answer-box" id="finalAnswerBox">
                    <!-- Final formatted output text -->
                </div>

                <div class="token-usage-bar" id="tokenUsageBar" style="display: none;">
                    <div class="usage-metric">Prompt tokens: <strong id="promptTokens">0</strong></div>
                    <div class="usage-metric">Completion tokens: <strong id="completionTokens">0</strong></div>
                    <div class="usage-metric">Total tokens: <strong id="totalTokens">0</strong></div>
                </div>
            </div>
        </main>
    </div>

    <script>
        const queryInput = document.getElementById("queryInput");
        const runBtn = document.getElementById("runBtn");
        const spinner = document.getElementById("spinner");
        const logConsole = document.getElementById("logConsole");
        const finalAnswerBox = document.getElementById("finalAnswerBox");
        const tokenUsageBar = document.getElementById("tokenUsageBar");
        const promptTokensSpan = document.getElementById("promptTokens");
        const completionTokensSpan = document.getElementById("completionTokens");
        const totalTokensSpan = document.getElementById("totalTokens");

        // Schema loader
        async function loadSchema() {
            const schemaList = document.getElementById("schemaList");
            try {
                const res = await fetch("/api/schema");
                if (res.status === 200) {
                    const data = await res.json();
                    renderSchema(data.schema);
                } else {
                    schemaList.innerHTML = '<div style="color: var(--danger-red); text-align: center; font-size: 0.85rem;">Failed to fetch schema</div>';
                }
            } catch (err) {
                schemaList.innerHTML = '<div style="color: var(--danger-red); text-align: center; font-size: 0.85rem;">MCP Server Offline</div>';
            }
        }

        function renderSchema(schemaStr) {
            const schemaList = document.getElementById("schemaList");
            schemaList.innerHTML = "";

            if (!schemaStr || schemaStr.startsWith("Error")) {
                schemaList.innerHTML = '<div style="color: var(--text-secondary); text-align: center; font-size: 0.85rem;">No tables discovered.</div>';
                return;
            }

            // Simple parser for table format returned by Go MCP Server: "Table: <name>\n  - <col> (<type>)"
            const sections = schemaStr.split("\n\n");
            sections.forEach(sec => {
                const lines = sec.trim().split("\n");
                if (lines[0].startsWith("Table: ")) {
                    const tableName = lines[0].replace("Table: ", "").trim();
                    
                    const item = document.createElement("div");
                    item.className = "schema-table-item";

                    const header = document.createElement("div");
                    header.className = "schema-table-header";
                    header.innerHTML = "<span>" + tableName + "</span><span style=\"font-size:0.75rem; opacity:0.6;\">▼</span>";

                    const columnsDiv = document.createElement("div");
                    columnsDiv.className = "schema-columns";

                    for (let i = 1; i < lines.length; i++) {
                        const colLine = lines[i].replace("- ", "").trim();
                        const parts = colLine.split(" ");
                        if (parts.length >= 2) {
                            const colName = parts[0];
                            const colType = parts.slice(1).join(" ").replace("(", "").replace(")", "");
                            columnsDiv.innerHTML += "<div class=\"schema-column-detail\"><span>" + colName + "</span><span class=\"schema-column-type\">" + colType + "</span></div>";
                        }
                    }

                    header.addEventListener("click", () => {
                        const isVisible = columnsDiv.style.display === "flex";
                        columnsDiv.style.display = isVisible ? "none" : "flex";
                        header.querySelector("span:last-child").textContent = isVisible ? "▼" : "▲";
                    });

                    item.appendChild(header);
                    item.appendChild(columnsDiv);
                    schemaList.appendChild(item);
                }
            });
        }

        document.getElementById("refreshSchema").addEventListener("click", loadSchema);
        window.addEventListener("DOMContentLoaded", loadSchema);

        // Run agent execution stream
        runBtn.addEventListener("click", () => {
            const question = queryInput.value.trim();
            if (!question) return;

            // Reset UI
            logConsole.innerHTML = "";
            finalAnswerBox.style.display = "none";
            finalAnswerBox.innerHTML = "";
            tokenUsageBar.style.display = "none";
            
            runBtn.disabled = true;
            spinner.style.display = "block";

            // Establish Server-Sent Events stream
            const encodedQ = encodeURIComponent(question);
            const eventSource = new EventSource("/stream?question=" + encodedQ);

            let tokenAccumulator = "";
            let currentTokenEl = null;

            eventSource.addEventListener("info", (e) => {
                const el = document.createElement("div");
                el.className = "log-line system";
                el.textContent = "[Info] " + JSON.parse(e.data);
                logConsole.appendChild(el);
                logConsole.scrollTop = logConsole.scrollHeight;
            });

            eventSource.addEventListener("tool_start", (e) => {
                const args = JSON.parse(e.data);
                const el = document.createElement("details");
                el.className = "log-line tool tool-box";
                el.innerHTML = "<summary>⚡ Executing tool arguments...</summary><pre>" + args + "</pre>";
                logConsole.appendChild(el);
                logConsole.scrollTop = logConsole.scrollHeight;
                
                // Clear any running text streaming elements
                currentTokenEl = null;
            });

            eventSource.addEventListener("tool_end", (e) => {
                const output = JSON.parse(e.data);
                const el = document.createElement("details");
                el.className = "log-line tool tool-box";
                el.innerHTML = "<summary>✔️ Tool response returned</summary><pre>" + output + "</pre>";
                logConsole.appendChild(el);
                logConsole.scrollTop = logConsole.scrollHeight;
                
                // Clear any running text streaming elements
                currentTokenEl = null;
            });

            eventSource.addEventListener("token", (e) => {
                const token = JSON.parse(e.data);
                if (!currentTokenEl) {
                    currentTokenEl = document.createElement("div");
                    currentTokenEl.className = "log-line token";
                    logConsole.appendChild(currentTokenEl);
                }
                currentTokenEl.textContent += token;
                logConsole.scrollTop = logConsole.scrollHeight;
            });

            eventSource.addEventListener("llm_end", (e) => {
                const usage = JSON.parse(e.data);
                promptTokensSpan.textContent = usage.prompt_tokens;
                completionTokensSpan.textContent = usage.completion_tokens;
                totalTokensSpan.textContent = usage.total_tokens;
                tokenUsageBar.style.display = "flex";
            });

            eventSource.addEventListener("final_answer", (e) => {
                const answer = JSON.parse(e.data);
                
                // Format final answer markdown simply
                let html = answer
                    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                    .replace(/\*(.*?)\*/g, "<em>$1</em>")
                    .replace(/\n/g, "<br>")
                    .replace(/Download Link: (http:\/\/localhost:\d+\/download\/[^\s]+)/g, "Download Link: <a href=\"$1\" target=\"_blank\" style=\"color:var(--primary-green); font-weight:700; text-decoration:underline;\">Click here to download Excel report</a>");

                finalAnswerBox.innerHTML = "<h3>Final Response</h3><p style=\"margin-top:0.75rem;\">" + html + "</p>";
                finalAnswerBox.style.display = "block";
                
                eventSource.close();
                runBtn.disabled = false;
                spinner.style.display = "none";
            });

            eventSource.addEventListener("error", (e) => {
                const errorMsg = JSON.parse(e.data);
                const el = document.createElement("div");
                el.className = "log-line system";
                el.style.color = "var(--danger-red)";
                el.textContent = "[Error] " + errorMsg;
                logConsole.appendChild(el);
                
                eventSource.close();
                runBtn.disabled = false;
                spinner.style.display = "none";
            });

            eventSource.onerror = (err) => {
                eventSource.close();
                runBtn.disabled = false;
                spinner.style.display = "none";
            };
        });
    </script>
</body>
</html>
`
